-- -----------------------------------------------------
-- Table `GPASSO`.`GID001MB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPASSO`.`GID001MB` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `GPASSO`.`GID001MB` (
  `MKR_ID` INT NULL DEFAULT NULL,
  `DT_CREATED` DATETIME NULL DEFAULT NULL,
  `ATH_ID` INT NULL DEFAULT NULL,
  `DT_MODIFIED` DATETIME NULL DEFAULT NULL,
  `FOR_USR_ID` INT NOT NULL DEFAULT NULL,
  `USR_ID` INT NOT NULL DEFAULT NULL,
  `GRP_ID` INT NOT NULL,
  `ACCT_TYPE` VARCHAR(45) NULL,
  `ADMIN_FLG` VARCHAR(45) NULL,
  `EMP_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`GRP_ID`, `USR_ID`, `FOR_USR_ID`),
  CONSTRAINT `FK_GRP001MB_GROUP_ID`
    FOREIGN KEY (`GRP_ID`)
    REFERENCES `GPASSO`.`GRP001MB` (`GRP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SID001MB_USR_ID`
    FOREIGN KEY (`FOR_USR_ID`)
    REFERENCES `GPASSO`.`SID001MB` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `FK_SID001MB_USR_ID_idx` ON `GPASSO`.`GID001MB` (`FOR_USR_ID` ASC);

SHOW WARNINGS;

