-- -----------------------------------------------------
-- Table `GPASSO`.`ROLE001MB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GPASSO`.`ROLE001MB` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `GPASSO`.`ROLE001MB` (
  `_ID` INT(11) NOT NULL DEFAULT NULL,
  `PRTL_ID` INT(11) NOT NULL DEFAULT NULL,
  `ROLE_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `STATUS` VARCHAR(45) NULL DEFAULT NULL,
  `DT_CREATED` DATETIME NULL DEFAULT NULL,
  `DT_MODIFIED` DATETIME NULL DEFAULT NULL,
  `MKR_ID` INT NULL DEFAULT NULL,
  `ATH_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`_ID`, `PRTL_ID`),
  CONSTRAINT `FK_ROLE001MB_PRTL_ID`
    FOREIGN KEY (`PRTL_ID`)
    REFERENCES `GPASSO`.`PRTL002MB` (`_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = COMPACT;

SHOW WARNINGS;
CREATE INDEX `FK_ROLE001MB_PRTL_ID_idx` ON `GPASSO`.`ROLE001MB` (`PRTL_ID` ASC);

SHOW WARNINGS;

